name: umrahrahat-CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # Step 3: Set up PHP
      # - name: Setup PHP 
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.2'
      #     extensions: mbstring, bcmath, pdo_mysql
      #     ini-values: post_max_size=256M, upload_max_filesize=256M
      #     coverage: none

      # Step 4: Copy .env file
      - name: Copy .env file
        run: cp .env.example .env

      # Step 5: Generate app key
      - name: Generate app key
        run: php artisan key:generate

      # Step 6: Install MySQL and set root password
      # - name: Set up MySQL and database
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y mysql-server
      #     sudo systemctl start mysql
      #     sudo systemctl enable mysql
      #     sleep 10 # Wait for MySQL to initialize
          # Set root password to 'root'
          # sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          # # Create the database
          # mysql -u root -proot -e "CREATE DATABASE umrahrahat;"

      # Step 7: Run migrations and seed database
      # - name: Run migrations
      #   env:
      #     DB_CONNECTION: mysql
      #     DB_DATABASE: umrahrahat
      #     DB_USERNAME: root
      #     DB_PASSWORD: root
      #   run: php artisan migrate --seed

      # Step 8: Run tests
      # - name: Run tests
      #   env:
      #     APP_ENV: testing
      #     DB_CONNECTION: mysql
      #     DB_DATABASE: umrahrahat
      #     DB_USERNAME: root
      #     DB_PASSWORD: root
      #   run: php artisan test

      - name: Install curl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl


      - name: Test Image and CSS Links
        run: |
          find . -name "*.html" | while read file; do
            echo "Testing links in $file"
            grep -oP '(?<=src=")[^"]*' "$file" | while read url; do
              if [[ ! "$url" =~ ^https?:// ]]; then
                url="https://umrahrahat.com/$url"
              fi
              curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200" || echo "Broken image: $url"
            done
            grep -oP '(?<=href=")[^"]*\.css' "$file" | while read url; do
              if [[ ! "$url" =~ ^https?:// ]]; then
                url="https://umrahrahat.com/$url"
              fi
              curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200" || echo "Broken CSS: $url"
            done
          done
