name: umrahrahat-CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # Step 3: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # Step 4: Copy .env file
      - name: Copy .env file
        run: cp .env.example .env

      # Step 5: Generate app key
      - name: Generate app key
        run: php artisan key:generate
        
  deploy:
    name: Deploy to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to FTP
      - name: Deploy to FTP
        uses: appleboy/ftp-action@latest
        with:
          host: ${{ secrets.FTP_HOST }}  # FTP host (e.g., ftp.umrahrahat.com)
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          port: ${{ secrets.FTP_PORT }}  # FTP port (usually 21)
          local-dir: ./  # Local directory to upload (usually the root directory)
          remote-dir: /home/umrahrahat/public_html  # Remote directory in cPanel

      # Step 3: Install curl dependencies
      - name: Install curl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      # Step 4: Test Image and CSS Links
      - name: Test Image and CSS Links
        run: |
          find . -name "*.html" | while read file; do
            echo "Testing links in $file"
            grep -oP '(?<=src=")[^"]*' "$file" | while read url; do
              if [[ ! "$url" =~ ^https?:// ]]; then
                url="https://umrahrahat.com/$url"
              fi
              curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200" || echo "Broken image: $url"
            done
            grep -oP '(?<=href=")[^"]*\.css' "$file" | while read url; do
              if [[ ! "$url" =~ ^https?:// ]]; then
                url="https://umrahrahat.com/$url"
              fi
              curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200" || echo "Broken CSS: $url"
            done
          done
