name : umrahrahat-CICD

on: 
  push:
      branches:
        - main
  pull_request:
      branches:
        - main
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:

    #step 1: checkout the repositary
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix broken packages and update
        run: |
          sudo apt-get install -f
          sudo dpkg --configure -a
          sudo apt-get update -y
          sudo apt-get install --reinstall liblzma-dev 
     
    #step 2: setup PHP
      - name:  Setup PHP 
        uses:  shivammathur/setup-php@v2
        with:
          php-version:  '8.2'
          extensions:  mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage:  none

    #step 3: Install composer dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

    # step 4: Set up the environment file
      - name: Copy .env file
        run: cp .env.example .env

    #step 5: generate application key
      - name: Generate app key
        run: php artisan key:generate
    #step 6: setup the database
      - name: Set up database
        run:  |
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sleep 10 # Wait for MySQL to initialize
          mysql -e "CREATE DATABASE umrahrahat;"

    #step 7: run migrations and seed database
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: umrahrahat
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: php artisan migrate --seed

    #step 8: Run tests
      - name: Run tests
        env:
           APP_ENV: testing
           DB_CONNECTION: mysql
           DB_DATABASE: umrahrahat
           DB_USERNAME: root
           DB_PASSWORD: ""
        run: php artisan test


          

          
    
